export const Post=[
    {
        id:'1651892665895',
        type:'photo',
        content:'All core systems are now on',
        photos:'https://pbs.twimg.com/media/GNwosctXMAENyqL?format=jpg&name=small',
        account:{
            avatar:'https://pbs.twimg.com/profile_images/1780044485541699584/p78MCn3B_400x400.jpg',
            username:'elonmusk',
            fullName:'Elon Musk ',
        },
		stats: {
			comments: 43535,
			repost: 3434,
			like: 96946,
			view: '101 B'
		}
    },
    {
        id:'1651895',
        type:'photo',
        content:'Images generated in ChatGPT and our API now include metadata using C2PA specifications . This allows anyone (including social platforms and content distributors) to see that an image was generated by our products. ',
        photos:'https://pbs.twimg.com/media/GFrC3NyaAAIxcPw?format=jpg&name=small',
        account:{
            avatar:'https://pbs.twimg.com/profile_images/1634058036934500352/b4F1eVpJ_400x400.jpg',
            username:'OpenAI',
            fullName:'OpenAI',
        },
		stats: {
			comments: 1265,
			repost: 2684,
			like: 92156,
			view: '82 B'
		}
    },
    {
        id:'1652665895',
        type:'photo',
        content:'Starships preparing for spaceflight',
        photos:'https://pbs.twimg.com/media/GNUa6dAaUAALO-D?format=jpg&name=900x900',
        account:{
            avatar:'https://pbs.twimg.com/profile_images/1780044485541699584/p78MCn3B_400x400.jpg',
            username:'elonmusk',
            fullName:'Elon Musk',
        },
		stats: {
			comments: 1225,
			repost: 934,
			like: 9546,
			view: '221 B'
		}
    },  
    {
        id:'100002665895',
        type:'photo',
        content:'All core systems are now on',
        photos:'https://pbs.twimg.com/media/GNwosctXMAENyqL?format=jpg&name=small',
        account:{
            avatar:'https://pbs.twimg.com/profile_images/1780044485541699584/p78MCn3B_400x400.jpg',
            username:'elonmusk',
            fullName:'Elon Musk ',
        },
		stats: {
			comments: 43535,
			repost: 3434,
			like: 96946,
			view: '101 B'
		}
    },
    {
        id:'1098895',
        type:'photo',
        content:'Images generated in ChatGPT and our API now include metadata using C2PA specifications . This allows anyone (including social platforms and content distributors) to see that an image was generated by our products. ',
        photos:'https://pbs.twimg.com/media/GFrC3NyaAAIxcPw?format=jpg&name=small',
        account:{
            avatar:'https://pbs.twimg.com/profile_images/1634058036934500352/b4F1eVpJ_400x400.jpg',
            username:'OpenAI',
            fullName:'OpenAI',
        },
		stats: {
			comments: 1265,
			repost: 2684,
			like: 92156,
			view: '82 B'
		}
    },
    {
        id:'16000665895',
        type:'photo',
        content:'Starships preparing for spaceflight',
        photos:'https://pbs.twimg.com/media/GNUa6dAaUAALO-D?format=jpg&name=900x900',
        account:{
            avatar:'https://pbs.twimg.com/profile_images/1780044485541699584/p78MCn3B_400x400.jpg',
            username:'elonmusk',
            fullName:'Elon Musk',
        },
		stats: {
			comments: 1225,
			repost: 934,
			like: 9546,
			view: '221 B'
		}
    }, 
    {
        id:'100820',
        type:'photo',
        content:'All core systems are now on',
        photos:'https://pbs.twimg.com/media/GNwosctXMAENyqL?format=jpg&name=small',
        account:{
            avatar:'https://pbs.twimg.com/profile_images/1780044485541699584/p78MCn3B_400x400.jpg',
            username:'elonmusk',
            fullName:'Elon Musk ',
        },
		stats: {
			comments: 43535,
			repost: 3434,
			like: 96946,
			view: '101 B'
		}
    },
    {
        id:'12001895',
        type:'photo',
        content:'Images generated in ChatGPT and our API now include metadata using C2PA specifications . This allows anyone (including social platforms and content distributors) to see that an image was generated by our products. ',
        photos:'https://pbs.twimg.com/media/GFrC3NyaAAIxcPw?format=jpg&name=small',
        account:{
            avatar:'https://pbs.twimg.com/profile_images/1634058036934500352/b4F1eVpJ_400x400.jpg',
            username:'OpenAI',
            fullName:'OpenAI',
        },
		stats: {
			comments: 1265,
			repost: 2684,
			like: 92156,
			view: '82 B'
		}
    },
    {
        id:'16585',
        type:'photo',
        content:'Starships preparing for spaceflight',
        photos:'https://pbs.twimg.com/media/GNUa6dAaUAALO-D?format=jpg&name=900x900',
        account:{
            avatar:'https://pbs.twimg.com/profile_images/1780044485541699584/p78MCn3B_400x400.jpg',
            username:'elonmusk',
            fullName:'Elon Musk',
        },
		stats: {
			comments: 1225,
			repost: 934,
			like: 9546,
			view: '221 B'
		}
    }, 
    {
        id:'651695',
        type:'photo',
        content:'All core systems are now on',
        photos:'https://pbs.twimg.com/media/GNwosctXMAENyqL?format=jpg&name=small',
        account:{
            avatar:'https://pbs.twimg.com/profile_images/1780044485541699584/p78MCn3B_400x400.jpg',
            username:'elonmusk',
            fullName:'Elon Musk ',
        },
		stats: {
			comments: 43535,
			repost: 3434,
			like: 96946,
			view: '101 B'
		}
    },
    {
        id:'895',
        type:'photo',
        content:'Images generated in ChatGPT and our API now include metadata using C2PA specifications . This allows anyone (including social platforms and content distributors) to see that an image was generated by our products. ',
        photos:'https://pbs.twimg.com/media/GFrC3NyaAAIxcPw?format=jpg&name=small',
        account:{
            avatar:'https://pbs.twimg.com/profile_images/1634058036934500352/b4F1eVpJ_400x400.jpg',
            username:'OpenAI',
            fullName:'OpenAI',
        },
		stats: {
			comments: 1265,
			repost: 2684,
			like: 92156,
			view: '82 B'
		}
    },
    {
        id:'65895',
        type:'photo',
        content:'Starships preparing for spaceflight',
        photos:'https://pbs.twimg.com/media/GNUa6dAaUAALO-D?format=jpg&name=900x900',
        account:{
            avatar:'https://pbs.twimg.com/profile_images/1780044485541699584/p78MCn3B_400x400.jpg',
            username:'elonmusk',
            fullName:'Elon Musk',
        },
		stats: {
			comments: 1225,
			repost: 934,
			like: 9546,
			view: '221 B'
		}
    }, 
    {
        id:'151866',
        type:'photo',
        content:'All core systems are now on',
        photos:'https://pbs.twimg.com/media/GNwosctXMAENyqL?format=jpg&name=small',
        account:{
            avatar:'https://pbs.twimg.com/profile_images/1780044485541699584/p78MCn3B_400x400.jpg',
            username:'elonmusk',
            fullName:'Elon Musk ',
        },
		stats: {
			comments: 43535,
			repost: 3434,
			like: 96946,
			view: '101 B'
		}
    },
    {
        id:'1655',
        type:'photo',
        content:'Images generated in ChatGPT and our API now include metadata using C2PA specifications . This allows anyone (including social platforms and content distributors) to see that an image was generated by our products. ',
        photos:'https://pbs.twimg.com/media/GFrC3NyaAAIxcPw?format=jpg&name=small',
        account:{
            avatar:'https://pbs.twimg.com/profile_images/1634058036934500352/b4F1eVpJ_400x400.jpg',
            username:'OpenAI',
            fullName:'OpenAI',
        },
		stats: {
			comments: 1265,
			repost: 2684,
			like: 92156,
			view: '82 B'
		}
    },
    {
        id:'1652665895',
        type:'photo',
        content:'Starships preparing for spaceflight',
        photos:'https://pbs.twimg.com/media/GNUa6dAaUAALO-D?format=jpg&name=900x900',
        account:{
            avatar:'https://pbs.twimg.com/profile_images/1780044485541699584/p78MCn3B_400x400.jpg',
            username:'elonmusk',
            fullName:'Elon Musk',
        },
		stats: {
			comments: 1225,
			repost: 934,
			like: 9546,
			view: '221 B'
		}
    }
]